language: go
services:
  - docker
branches:
  only:
    - travis-ci
addons:
  ssh_known_hosts: "${SSH_HOST}"
  sonarcloud:
    organization: kiwsan
    token:
      secure: "${SONAR_CLOUD_TOKEN}"
before_install:
  - openssl aes-256-cbc -K $encrypted_decd9e9f07c0_key -iv $encrypted_decd9e9f07c0_iv
    -in travis_rsa.enc -out travis_rsa -d
  - chmod 600 travis_rsa
  - mv travis_rsa ~/.ssh/travis_rsa
before_script:
  - sed 's/${ENV_DATABASE_HOST}/'"${DATABASE_HOST}"'/g; s/${ENV_DATABASE_USER}/'"${DATABASE_USER}"'/g;
    s/${ENV_DATABASE_PASSWORD}/'"${DATABASE_PASSWORD}"'/g; s/${ENV_DATABASE_PORT}/'"${DATABASE_PORT}"'/g;
    s/${ENV_RABBITMQ_HOST}/'"${RABBITMQ_HOST}"'/g; s/${ENV_RABBITMQ_USER}/'"${RABBITMQ_USER}"'/g;
    s/${ENV_RABBITMQ_PASSWORD}/'"${RABBITMQ_PASSWORD}"'/g; s/${ENV_RABBITMQ_PORT}/'"${RABBITMQ_PORT}"'/g;'
    appsettings.yml > appsettings.${TRAVIS_ENVIRONMENT}.yml
  - docker build -t golang-identity-service:${TRAVIS_COMMIT} .
  - docker run -d -p 127.0.0.1:8000:8000 golang-identity-service:${TRAVIS_COMMIT}
script:
  - sonar-scanner
  - echo "$DOCKER_PASSWORD" | docker login $DOCKER_CUSTOM_HOST -u "$DOCKER_USERNAME"
    --password-stdin
  - docker tag golang-identity-service:${TRAVIS_COMMIT} $DOCKER_CUSTOM_HOST/golang-identity-service:${TRAVIS_COMMIT}
  - docker push $DOCKER_CUSTOM_HOST/golang-identity-service:${TRAVIS_COMMIT}
  - docker tag golang-identity-service:${TRAVIS_COMMIT} $DOCKER_CUSTOM_HOST/golang-identity-service:latest
  - docker push $DOCKER_CUSTOM_HOST/golang-identity-service:latest
after_success:
  - set -xe
  - rm -rf .git
  - eval "$(ssh-agent -s)" && ssh-add ~/.ssh/travis_rsa && ssh -o "StrictHostKeyChecking=no"
    ${REMOTE_USER}@${SSH_HOST} -v exit
  - git init
  - git remote add deploy "${REMOTE_USER}@${SSH_HOST}:/opt/go-auth-service" && git config
    user.name "Travis CI" && git config user.email "kiwsan+travis@gmail.com" && git
    status && git add docker-compose.yml && git commit -m "deploy"
  - git push --force deploy master
  - ssh -l ${REMOTE_USER} ${SSH_HOST} "docker-compose -f ${REMOTE_APP_DIR}/public/docker-compose.${TRAVIS_ENVIRONMENT}.yml
    pull && docker-compose -f ${REMOTE_APP_DIR}/public/docker-compose.${TRAVIS_ENVIRONMENT}.yml
    up -d"
notifications:
  email: false    # default notification method
  slack:
    rooms: # https://docs.travis-ci.com/user/encryption-keys/
      secure: 4U/t7FtbJzWaiBJOPVMmAOnpqtau6HTcWA6fQD0r8sOBVSt19jeK940rUp8bk8E9gz8mT3cbXdR0+TE5XDhf5gqqLRNXuj7kFtXM1Ru5wqEHJAlci0aDja8xOeqZ9/wzTurEBIa4lfIj926eoVtVBSLre/oHqh9WEpbZpDcgGIZfU49jIAS5mVQnw48bHN3DmMjFbrJEmHrw6p6wMRuAFwMwpnIR503yJZD5fNGVtOXvcGxTV0Ov1iM+Aqm18FFrJv986HA5VQUXALhyQTDaleqsG5q24riNS8KFS64/1/uod1e3tE330+I2i6gb+CPorKnsHaLgvIcthNEX6+E7gUcpmQIol6iIod2LACIoyS0xV+l8GjqoJxNZIswWw2MmTukEv0WhpkEZMUQdxbgwLKU1I+fn8hX+cL8lZoPab/7oG2+jAiI8I2KAg0EFzi4iWDGikOEMEG/DCqkfqjStYLbKGd6yLA7sRhjlyGoXegNfC0opVcPLRLlT+32xRjtSRoYa5A5VFXyZ7ebyD2d2Asd7rNl+MbSbMoRZbr177qYTpes7Gu9lvTztnJXmaEImxiM16RYX4//vfnz/AXxVvF+JG9HUSFMF4Zo3wbaqLTQVKRRL3+Cv57x4bVRwZsAcosq74/yeDxs9owzj10uMWvAoaby+YboXljGKBm7HIO4=
    on_success: always  # change: send a notification when the build status changes.
    on_failure: always  # always: always send a notification.
