language: go
services:
  - docker
branches:
  only:
    - travis-ci
addons:
  ssh_known_hosts: "${SSH_HOST}"
  sonarcloud:
    organization: kiwsan
    token:
      secure: "${SONAR_CLOUD_TOKEN}"
before_install:
  - bash scripts/ssh-build.sh
before_script:
  - bash scripts/variable-build.sh
  - bash scripts/docker-build.sh
script:
  - sonar-scanner
  - bash scripts/docker-push.sh
after_success:
  - set -xe
  - bash scripts/deploy.sh
notifications:
  email: false    # default notification method
  slack:
    rooms: # https://docs.travis-ci.com/user/encryption-keys/
      secure: 4U/t7FtbJzWaiBJOPVMmAOnpqtau6HTcWA6fQD0r8sOBVSt19jeK940rUp8bk8E9gz8mT3cbXdR0+TE5XDhf5gqqLRNXuj7kFtXM1Ru5wqEHJAlci0aDja8xOeqZ9/wzTurEBIa4lfIj926eoVtVBSLre/oHqh9WEpbZpDcgGIZfU49jIAS5mVQnw48bHN3DmMjFbrJEmHrw6p6wMRuAFwMwpnIR503yJZD5fNGVtOXvcGxTV0Ov1iM+Aqm18FFrJv986HA5VQUXALhyQTDaleqsG5q24riNS8KFS64/1/uod1e3tE330+I2i6gb+CPorKnsHaLgvIcthNEX6+E7gUcpmQIol6iIod2LACIoyS0xV+l8GjqoJxNZIswWw2MmTukEv0WhpkEZMUQdxbgwLKU1I+fn8hX+cL8lZoPab/7oG2+jAiI8I2KAg0EFzi4iWDGikOEMEG/DCqkfqjStYLbKGd6yLA7sRhjlyGoXegNfC0opVcPLRLlT+32xRjtSRoYa5A5VFXyZ7ebyD2d2Asd7rNl+MbSbMoRZbr177qYTpes7Gu9lvTztnJXmaEImxiM16RYX4//vfnz/AXxVvF+JG9HUSFMF4Zo3wbaqLTQVKRRL3+Cv57x4bVRwZsAcosq74/yeDxs9owzj10uMWvAoaby+YboXljGKBm7HIO4=
    on_success: always  # change: send a notification when the build status changes.
    on_failure: always  # always: always send a notification.
