language: go

services:
  - docker

script:
  - docker build -t ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} .
  - docker run -d -p 8000:8000 ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT}
  - curl "172.0.0.1:8000"
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
  - echo "$DOCKER_PASSWORD" | docker login $DOCKER_CUSTOM_HOST -u "$DOCKER_USERNAME" --password-stdin  
  - docker tag ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} $DOCKER_CUSTOM_HOST/${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT}
  - docker push $DOCKER_CUSTOM_HOST/${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT}
  - docker build --no-cache -t ${TRAVIS_REPO_SLUG}:latest .
  - docker tag ${TRAVIS_REPO_SLUG}:latest $DOCKER_CUSTOM_HOST/${TRAVIS_REPO_SLUG}:latest
  - docker push $DOCKER_CUSTOM_HOST/${TRAVIS_REPO_SLUG}:latest
    
addons:
  sonarcloud:
    organization: "kiwsan"
    token:
      secure: "${SONAR_CLOUD_TOKEN}" # encrypted value of your token
