appname: identity-service

database:
  host:     "${DATABASE_HOST}"
  user:     "${DATABASE_USER}"
  password: "${DATABASE_PASSWORD}" #The database user is required administrator roles.
  port:     ${DATABASE_PORT}

contacts:
  - name: i kiwsan
    email: admin@kiwsan.com
