appname: identity-service

database:
  host:     "${HOST}"
  user:     "${USER}"
  password: "${PASSWORD}" #The database user is required administrator roles.
  port:     ${PORT}

contacts:
  - name: i kiwsan
    email: admin@kiwsan.com
