appname: identity-service

database:
  host:     "localhost"
  user:     "root"
  password: "Str0ngPassword!" #The database user is required administrator roles.
  port:     "27017"

rabbitmq:
  host: "localhost"
  user: "user"
  password: "secret"
  port: "5672"

contacts:
  - name: "i kiwsan"
    email: "admin@kiwsan.com"
