#!/bin/bash

sed 's/${ENV_DATABASE_HOST}/'"${DATABASE_HOST}"'/g; s/${ENV_DATABASE_USER}/'"${DATABASE_USER}"'/g; s/${ENV_DATABASE_PASSWORD}/'"${DATABASE_PASSWORD}"'/g; s/${ENV_DATABASE_PORT}/'"${DATABASE_PORT}"'/g; s/${ENV_RABBITMQ_HOST}/'"${RABBITMQ_HOST}"'/g; s/${ENV_RABBITMQ_USER}/'"${RABBITMQ_USER}"'/g; s/${ENV_RABBITMQ_PASSWORD}/'"${RABBITMQ_PASSWORD}"'/g; s/${ENV_RABBITMQ_PORT}/'"${RABBITMQ_PORT}"'/g;' appsettings.yml >appsettings.${TRAVIS_ENVIRONMENT}.yml
